"""add user_id foreign key to user_job_profile

Revision ID: 966ca07103d2
Revises: d190a24cb9c4
Create Date: 2026-06-28 11:56:06.218541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '966ca07103d2'
down_revision: Union[str, Sequence[str], None] = 'd190a24cb9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userjobprofile', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'userjobprofile', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userjobprofile', type_='foreignkey')
    op.drop_column('userjobprofile', 'user_id')
    # ### end Alembic commands ###
