"""split user_job_profile location into city/country columns

Revision ID: d190a24cb9c4
Revises: 1fbecb557442
Create Date: 2026-06-28 11:52:38.799988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd190a24cb9c4'
down_revision: Union[str, Sequence[str], None] = '1fbecb557442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userjobprofile',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_occupation', sa.Enum('SOFTWARE_ENGINEER', 'SOFTWARE_DEVELOPER', 'FRONT_END_WEB_DEVELOPER', 'JAVA_DEVELOPER', 'SQL_DEVELOPER', 'WEB_DEVELOPER', 'WEB_ADMINISTRATOR', 'MOBILE_APPLICATION_DEVELOPER', 'COMPUTER_PROGRAMMER', 'DATA_ARCHITECT', 'DATABASE_MANAGER', 'BUSINESS_INTELLIGENCE_DEVELOPER', 'INFORMATION_SECURITY_ANALYST', 'IT_MANAGER', 'PRODUCT_MANAGER', 'PRODUCT_MARKETING_MANAGER', 'TECHNICAL_PRODUCT_MANAGER', 'UX_DESIGNER', 'UI_DESIGNER', 'UI_DEVELOPER', 'GRAPHIC_DESIGNER', 'ART_DIRECTOR', 'ILLUSTRATOR', 'MULTIMEDIA_ANIMATOR', 'DIGITAL_MARKETING_SPECIALIST', 'MARKETING_MANAGER', 'MARKETING_ANALYST', 'SEARCH_ENGINE_OPTIMIZATION_SPECIALIST', 'SOCIAL_MEDIA_MANAGER', 'CONTENT_MARKETING_MANAGER', 'GROWTH_MARKETER', 'PERFORMANCE_MARKETING_MANAGER', 'PAID_MEDIA_SPECIALIST', 'WRITER', 'EDITOR', 'INSTRUCTIONAL_DESIGNER', 'TECHNICAL_WRITER', name='occupation'), nullable=False),
    sa.Column('desired_occupation', sa.Enum('SOFTWARE_ENGINEER', 'SOFTWARE_DEVELOPER', 'FRONT_END_WEB_DEVELOPER', 'JAVA_DEVELOPER', 'SQL_DEVELOPER', 'WEB_DEVELOPER', 'WEB_ADMINISTRATOR', 'MOBILE_APPLICATION_DEVELOPER', 'COMPUTER_PROGRAMMER', 'DATA_ARCHITECT', 'DATABASE_MANAGER', 'BUSINESS_INTELLIGENCE_DEVELOPER', 'INFORMATION_SECURITY_ANALYST', 'IT_MANAGER', 'PRODUCT_MANAGER', 'PRODUCT_MARKETING_MANAGER', 'TECHNICAL_PRODUCT_MANAGER', 'UX_DESIGNER', 'UI_DESIGNER', 'UI_DEVELOPER', 'GRAPHIC_DESIGNER', 'ART_DIRECTOR', 'ILLUSTRATOR', 'MULTIMEDIA_ANIMATOR', 'DIGITAL_MARKETING_SPECIALIST', 'MARKETING_MANAGER', 'MARKETING_ANALYST', 'SEARCH_ENGINE_OPTIMIZATION_SPECIALIST', 'SOCIAL_MEDIA_MANAGER', 'CONTENT_MARKETING_MANAGER', 'GROWTH_MARKETER', 'PERFORMANCE_MARKETING_MANAGER', 'PAID_MEDIA_SPECIALIST', 'WRITER', 'EDITOR', 'INSTRUCTIONAL_DESIGNER', 'TECHNICAL_WRITER', name='occupation'), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('current_location_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_location_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('desired_location_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('desired_location_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('remote_preference', sa.Enum('REMOTE', 'HYBRID', 'ONSITE', 'ANY', name='remotepreference'), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('userjobprofile')
    # ### end Alembic commands ###
